version: '3.9'

services:

  postgres:
    image: postgres:17

    container_name: meteoinsight-postgres

    restart: always

    environment:
      POSTGRES_DB: meteoinsight
      POSTGRES_USER: meteo
      POSTGRES_PASSWORD: meteo123

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: